Feat/ add configuration files
bewitching-eggs/core pull request #4
Opened 2024-03-07 14:04 UTC by Discipulus101

Add configuration files typescript, commitlint, husky and lint-staged

2024-03-11 15:22 UTC, Makvagabo approved these changes

2024-03-11 16:18 UTC, mrerberg commented
Давай впредь именовать пр-ы так же, как и на других проектах, только по-английски (потому что код в открытом доступе). Без feat и тд. Лишняя инфа

2024-03-11 16:31 UTC, mrerberg requested changes

2024-03-11 16:31 UTC, mrerberg commented on .changeset/rude-phones-tell.md
> +add configuration files typescript, commitlint, husky and lint-staged
Это можно чуть отредактировать:
Add configuration files for:
- …
- …

2024-03-11 16:31 UTC, mrerberg commented on packages/configs/README.md
> +Add to commitlint.config.js:
Полная инструкция звучала бы так:
Firstly, create commitlint file. Then, …

2024-03-11 16:31 UTC, mrerberg commented on packages/configs/README.md
> +Add to lint-staged.config.js:
Тоже самое, что и коммент про commitlint. А кстати, через package json можно это сделать? Без создания конфиг файла имею в виду

2024-03-11 16:31 UTC, mrerberg commented on packages/configs/README.md
> +  // add other rules that use paths:
Этот коммент лишний, можно удалить

2024-03-11 16:31 UTC, mrerberg commented on packages/configs/README.md
> +
В данном случае ты хотел разделить конфиги на серверный и браузерный. Но в каждом проекте 1 тс конфиг и называются они одинаково. Названия конфигов в проекте, который импортирует core, не должны быть разными

2024-03-11 16:31 UTC, mrerberg commented on packages/configs/README.md
> +
Мне кажется, вся эта секция (к которой прикреплен коммент) лишняя, выше же есть уже инструкция

2024-03-11 17:39 UTC, Discipulus101 commented on packages/configs/README.md
> +Add to lint-staged.config.js:
### **lint-staged**
Из того что я узнал в обсуждении этой темы, так сделать нельзя:  
https://github.com/lint-staged/lint-staged/issues/956
https://github.com/lint-staged/lint-staged/pull/1282

То есть вариант либо как в примере у нас: 
`module.exports = require('@bewitching-eggs/c/lint-staged');`

либо как в обсуждении, прописать запуск с указанием пути где лежит конфиг: 
`npx lint-staged -c node_modules/@org/shared-configs/lint-staged`

### **commitlint**
А вот в случае с commitlint, файл commitlint.config.js можно убрать и добавить конфиг через package.json

2024-03-12 05:23 UTC, mrerberg commented on packages/configs/README.md
> +Add to lint-staged.config.js:
Если можно сконфигурировать через package json, давай и для этого варианта добавим инструкцию. Она в приоритете

2024-03-12 14:15 UTC, Discipulus101 commented on .changeset/rude-phones-tell.md
> +add configuration files typescript, commitlint, husky and lint-staged
Сделал

2024-03-12 14:16 UTC, Discipulus101 commented on packages/configs/README.md
> +Add to commitlint.config.js:
Изменил

2024-03-12 14:19 UTC, Discipulus101 commented on packages/configs/README.md
> +Add to lint-staged.config.js:
Сделал инструкцию для добавления конфигурации commitlin в package.json

2024-03-12 14:19 UTC, Discipulus101 commented on packages/configs/README.md
> +  // add other rules that use paths:
Сделал

2024-03-12 14:19 UTC, Discipulus101 commented on packages/configs/README.md
> +
+

2024-03-12 14:27 UTC, mrerberg requested changes

2024-03-12 14:27 UTC, mrerberg commented on .changeset/rude-phones-tell.md
> + - typescript,
Если что, после конца элемента списка запятые ставить не надо, это же список

2024-03-12 14:27 UTC, mrerberg commented on packages/configs/README.md
> +  "references": [{ "path": "./tsconfig.node.json" }]
Тут надо вместо node vite поставить

2024-03-12 14:45 UTC, Discipulus101 commented on .changeset/rude-phones-tell.md
> + - typescript,
Исправил

2024-03-12 14:46 UTC, Discipulus101 commented on packages/configs/README.md
> +  "references": [{ "path": "./tsconfig.node.json" }]
Исправил

2024-03-12 14:51 UTC, mrerberg approved these changes

2024-03-12 15:04 UTC, merged