fix configurations husky and lint-staged
bewitching-eggs/core pull request #6
Opened 2024-03-15 15:45 UTC by Discipulus101

2024-03-16 09:55 UTC, mrerberg requested changes

2024-03-16 09:55 UTC, mrerberg commented on packages/configs/README.md
> +Run the prepare command.
Возьми из документации хаски, какую команду надо заранить

2024-03-16 09:55 UTC, mrerberg commented on packages/configs/README.md
> +Then copy files from directory: packages/configs/husky/hooks
Стоит как-то выделить путь в доке. Сделай это через бектики - "``"

2024-03-18 14:12 UTC, Discipulus101 commented on packages/configs/README.md
> +Run the prepare command.
Сделал:
Run the command: `npx husky init`
Then copy files from directory: `packages/configs/husky/hooks`
to husky directory in your project: `.husky/`

2024-03-18 14:13 UTC, Discipulus101 commented on packages/configs/README.md
> +Then copy files from directory: packages/configs/husky/hooks
Сделал

2024-03-18 14:15 UTC, mrerberg approved these changes

2024-03-18 14:17 UTC, merged